version: "3.9"

services:
  web:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
        TZ: ${TZ}
    container_name: go-mvc-app
    expose:
      - "8080"
    environment:
      - APP_ENV=${APP_ENV}
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
