version: "3.9"

services:
  web:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
        TZ: ${TZ}
    container_name: go-mvc-app
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV}
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
